### ISSUE TITLE
Add an option screwdrivercd_version to add links to the git source in the project links.

### ISSUE THREAD

**Issue by dwighthubbard** [yahoo/python-screwdrivercd#43]
Add an option for the version updater to add/update a source repository project link that links back to the github hash of the source used to build the package.

## Expected Behavior

If the flag is true in the configuration, the generated package will have a project link that points back to the github url of the git hash with the source used to generate the package.

## Current Behavior

There is no source project_link

**Comment by patrasap0908** [comment]
@dwighthubbard, the expected result is for the utility to add a link to the commit's SHA hash that caused the package to get built to `metadata` section in setup.cfg, correct?

**Comment by patrasap0908** [comment]
> @dwighthubbard, the expected result is for the utility to add a link to the commit's SHA hash that caused the package to get built to `metadata` section in setup.cfg, correct?

Ignore this comment, take a look at https://github.com/yahoo/python-screwdrivercd/pull/107 whenever you get a chance.
